// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"my_knowledges/internal/biz"
	"my_knowledges/internal/conf"
	"my_knowledges/internal/data"
	"my_knowledges/internal/server"
	"my_knowledges/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewMySQL(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	domainRepo := data.NewDomainRepo(dataData, logger)
	domainUsecase := biz.NewDomainUsecase(domainRepo)
	domainService := service.NewDomainService(domainUsecase)
	knowledgeRepo := data.NewKnowledgeRepo(dataData, logger)
	knowledgeUsecase := biz.NewKnowledgeUsecase(knowledgeRepo)
	knowledgeService := service.NewKnowledgeService(knowledgeUsecase)
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	articleService := service.NewArticleService(articleUsecase)
	fileService := service.NewFileService(logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase, confData, logger)
	grpcServer := server.NewGRPCServer(confServer, confData, greeterService, domainService, knowledgeService, articleService, fileService, userService, logger)
	httpServer := server.NewHTTPServer(confServer, confData, greeterService, domainService, knowledgeService, articleService, fileService, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
