// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: knowledge/v1/knowledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 领域消息
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	BySort        int64                  `protobuf:"varint,7,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Domain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Domain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Domain) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Domain) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 获取领域列表请求
type ListDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

// 获取领域列表响应
type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Domain              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *ListDomainsResponse) GetItems() []*Domain {
	if x != nil {
		return x.Items
	}
	return nil
}

// 知识库消息
type Knowledge struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	DomainId          int64                  `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	ParentKnowledgeId int64                  `protobuf:"varint,6,opt,name=parent_knowledge_id,json=parentKnowledgeId,proto3" json:"parent_knowledge_id,omitempty"`
	Name              string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	BySort            int64                  `protobuf:"varint,9,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *Knowledge) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Knowledge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Knowledge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Knowledge) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Knowledge) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *Knowledge) GetParentKnowledgeId() int64 {
	if x != nil {
		return x.ParentKnowledgeId
	}
	return 0
}

func (x *Knowledge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Knowledge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Knowledge) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 创建知识库请求
type CreateKnowledgeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DomainId          int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	ParentKnowledgeId int64                  `protobuf:"varint,2,opt,name=parent_knowledge_id,json=parentKnowledgeId,proto3" json:"parent_knowledge_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BySort            int64                  `protobuf:"varint,5,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateKnowledgeRequest) Reset() {
	*x = CreateKnowledgeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeRequest) ProtoMessage() {}

func (x *CreateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKnowledgeRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *CreateKnowledgeRequest) GetParentKnowledgeId() int64 {
	if x != nil {
		return x.ParentKnowledgeId
	}
	return 0
}

func (x *CreateKnowledgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKnowledgeRequest) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 更新知识库请求
type UpdateKnowledgeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId          int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	ParentKnowledgeId int64                  `protobuf:"varint,3,opt,name=parent_knowledge_id,json=parentKnowledgeId,proto3" json:"parent_knowledge_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BySort            int64                  `protobuf:"varint,6,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateKnowledgeRequest) Reset() {
	*x = UpdateKnowledgeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeRequest) ProtoMessage() {}

func (x *UpdateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateKnowledgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateKnowledgeRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *UpdateKnowledgeRequest) GetParentKnowledgeId() int64 {
	if x != nil {
		return x.ParentKnowledgeId
	}
	return 0
}

func (x *UpdateKnowledgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 删除知识库请求
type DeleteKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeRequest) Reset() {
	*x = DeleteKnowledgeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeRequest) ProtoMessage() {}

func (x *DeleteKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKnowledgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取知识库树请求
type GetKnowledgeTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      int64                  `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeTreeRequest) Reset() {
	*x = GetKnowledgeTreeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeTreeRequest) ProtoMessage() {}

func (x *GetKnowledgeTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeTreeRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeTreeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *GetKnowledgeTreeRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

// 获取知识库树响应
type GetKnowledgeTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeTreeNode   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeTreeResponse) Reset() {
	*x = GetKnowledgeTreeResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeTreeResponse) ProtoMessage() {}

func (x *GetKnowledgeTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeTreeResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeTreeResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *GetKnowledgeTreeResponse) GetItems() []*KnowledgeTreeNode {
	if x != nil {
		return x.Items
	}
	return nil
}

// 知识库树节点
type KnowledgeTreeNode struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId          int64                  `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	ParentKnowledgeId int64                  `protobuf:"varint,3,opt,name=parent_knowledge_id,json=parentKnowledgeId,proto3" json:"parent_knowledge_id,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BySort            int64                  `protobuf:"varint,6,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	Children          []*KnowledgeTreeNode   `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KnowledgeTreeNode) Reset() {
	*x = KnowledgeTreeNode{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeTreeNode) ProtoMessage() {}

func (x *KnowledgeTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeTreeNode.ProtoReflect.Descriptor instead.
func (*KnowledgeTreeNode) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *KnowledgeTreeNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeTreeNode) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *KnowledgeTreeNode) GetParentKnowledgeId() int64 {
	if x != nil {
		return x.ParentKnowledgeId
	}
	return 0
}

func (x *KnowledgeTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeTreeNode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KnowledgeTreeNode) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

func (x *KnowledgeTreeNode) GetChildren() []*KnowledgeTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// 文章消息
type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	KnowledgeId     int64                  `protobuf:"varint,5,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	ParentArticleId int64                  `protobuf:"varint,6,opt,name=parent_article_id,json=parentArticleId,proto3" json:"parent_article_id,omitempty"`
	Title           string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Level           int32                  `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	BySort          int64                  `protobuf:"varint,10,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Article) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Article) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

func (x *Article) GetParentArticleId() int64 {
	if x != nil {
		return x.ParentArticleId
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Article) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 创建文章请求
type CreateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId     int64                  `protobuf:"varint,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	ParentArticleId int64                  `protobuf:"varint,2,opt,name=parent_article_id,json=parentArticleId,proto3" json:"parent_article_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Level           int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	BySort          int64                  `protobuf:"varint,6,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *CreateArticleRequest) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

func (x *CreateArticleRequest) GetParentArticleId() int64 {
	if x != nil {
		return x.ParentArticleId
	}
	return 0
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateArticleRequest) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 获取单个文章请求
type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新文章请求
type UpdateArticleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KnowledgeId     int64                  `protobuf:"varint,2,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	ParentArticleId int64                  `protobuf:"varint,3,opt,name=parent_article_id,json=parentArticleId,proto3" json:"parent_article_id,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Level           int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	BySort          int64                  `protobuf:"varint,7,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateArticleRequest) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

func (x *UpdateArticleRequest) GetParentArticleId() int64 {
	if x != nil {
		return x.ParentArticleId
	}
	return 0
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateArticleRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateArticleRequest) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 删除文章请求
type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取文章树请求
type GetArticleTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   int64                  `protobuf:"varint,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleTreeRequest) Reset() {
	*x = GetArticleTreeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleTreeRequest) ProtoMessage() {}

func (x *GetArticleTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleTreeRequest.ProtoReflect.Descriptor instead.
func (*GetArticleTreeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *GetArticleTreeRequest) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

// 获取文章树响应
type GetArticleTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArticleTreeNode     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleTreeResponse) Reset() {
	*x = GetArticleTreeResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleTreeResponse) ProtoMessage() {}

func (x *GetArticleTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleTreeResponse.ProtoReflect.Descriptor instead.
func (*GetArticleTreeResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *GetArticleTreeResponse) GetItems() []*ArticleTreeNode {
	if x != nil {
		return x.Items
	}
	return nil
}

// 文章树节点
type ArticleTreeNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KnowledgeId     int64                  `protobuf:"varint,2,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	ParentArticleId int64                  `protobuf:"varint,3,opt,name=parent_article_id,json=parentArticleId,proto3" json:"parent_article_id,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Level           int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	BySort          int64                  `protobuf:"varint,7,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	Children        []*ArticleTreeNode     `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleTreeNode) Reset() {
	*x = ArticleTreeNode{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleTreeNode) ProtoMessage() {}

func (x *ArticleTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleTreeNode.ProtoReflect.Descriptor instead.
func (*ArticleTreeNode) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *ArticleTreeNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleTreeNode) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

func (x *ArticleTreeNode) GetParentArticleId() int64 {
	if x != nil {
		return x.ParentArticleId
	}
	return 0
}

func (x *ArticleTreeNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleTreeNode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleTreeNode) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ArticleTreeNode) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

func (x *ArticleTreeNode) GetChildren() []*ArticleTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// 文章响应
type ArticleResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	KnowledgeId     int64                  `protobuf:"varint,5,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	ParentArticleId int64                  `protobuf:"varint,6,opt,name=parent_article_id,json=parentArticleId,proto3" json:"parent_article_id,omitempty"`
	Title           string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Level           int32                  `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	BySort          int64                  `protobuf:"varint,10,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArticleResponse) Reset() {
	*x = ArticleResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResponse) ProtoMessage() {}

func (x *ArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResponse.ProtoReflect.Descriptor instead.
func (*ArticleResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *ArticleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArticleResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ArticleResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *ArticleResponse) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

func (x *ArticleResponse) GetParentArticleId() int64 {
	if x != nil {
		return x.ParentArticleId
	}
	return 0
}

func (x *ArticleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ArticleResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ArticleResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ArticleResponse) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 排序知识库请求
type SortKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeSortItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortKnowledgeRequest) Reset() {
	*x = SortKnowledgeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortKnowledgeRequest) ProtoMessage() {}

func (x *SortKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*SortKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{19}
}

func (x *SortKnowledgeRequest) GetItems() []*KnowledgeSortItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 知识库排序项
type KnowledgeSortItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BySort        int64                  `protobuf:"varint,2,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSortItem) Reset() {
	*x = KnowledgeSortItem{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSortItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSortItem) ProtoMessage() {}

func (x *KnowledgeSortItem) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSortItem.ProtoReflect.Descriptor instead.
func (*KnowledgeSortItem) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{20}
}

func (x *KnowledgeSortItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeSortItem) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 排序知识库响应
type SortKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortKnowledgeResponse) Reset() {
	*x = SortKnowledgeResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortKnowledgeResponse) ProtoMessage() {}

func (x *SortKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*SortKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{21}
}

func (x *SortKnowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SortKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 排序文章请求
type SortArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ArticleSortItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortArticleRequest) Reset() {
	*x = SortArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortArticleRequest) ProtoMessage() {}

func (x *SortArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortArticleRequest.ProtoReflect.Descriptor instead.
func (*SortArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{22}
}

func (x *SortArticleRequest) GetItems() []*ArticleSortItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 文章排序项
type ArticleSortItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BySort        int64                  `protobuf:"varint,2,opt,name=by_sort,json=bySort,proto3" json:"by_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleSortItem) Reset() {
	*x = ArticleSortItem{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleSortItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleSortItem) ProtoMessage() {}

func (x *ArticleSortItem) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleSortItem.ProtoReflect.Descriptor instead.
func (*ArticleSortItem) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{23}
}

func (x *ArticleSortItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleSortItem) GetBySort() int64 {
	if x != nil {
		return x.BySort
	}
	return 0
}

// 排序文章响应
type SortArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ArticleTree   []*ArticleTreeNode     `protobuf:"bytes,3,rep,name=article_tree,json=articleTree,proto3" json:"article_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortArticleResponse) Reset() {
	*x = SortArticleResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortArticleResponse) ProtoMessage() {}

func (x *SortArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortArticleResponse.ProtoReflect.Descriptor instead.
func (*SortArticleResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{24}
}

func (x *SortArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SortArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SortArticleResponse) GetArticleTree() []*ArticleTreeNode {
	if x != nil {
		return x.ArticleTree
	}
	return nil
}

// 移动知识库请求
type MoveKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewParentId   int64                  `protobuf:"varint,2,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	DomainId      int64                  `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveKnowledgeRequest) Reset() {
	*x = MoveKnowledgeRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveKnowledgeRequest) ProtoMessage() {}

func (x *MoveKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*MoveKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{25}
}

func (x *MoveKnowledgeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveKnowledgeRequest) GetNewParentId() int64 {
	if x != nil {
		return x.NewParentId
	}
	return 0
}

func (x *MoveKnowledgeRequest) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

// 移动知识库响应
type MoveKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KnowledgeTree []*KnowledgeTreeNode   `protobuf:"bytes,3,rep,name=knowledge_tree,json=knowledgeTree,proto3" json:"knowledge_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveKnowledgeResponse) Reset() {
	*x = MoveKnowledgeResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveKnowledgeResponse) ProtoMessage() {}

func (x *MoveKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*MoveKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{26}
}

func (x *MoveKnowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveKnowledgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MoveKnowledgeResponse) GetKnowledgeTree() []*KnowledgeTreeNode {
	if x != nil {
		return x.KnowledgeTree
	}
	return nil
}

// 移动文章请求
type MoveArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewParentId   int64                  `protobuf:"varint,2,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	KnowledgeId   int64                  `protobuf:"varint,3,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveArticleRequest) Reset() {
	*x = MoveArticleRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArticleRequest) ProtoMessage() {}

func (x *MoveArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArticleRequest.ProtoReflect.Descriptor instead.
func (*MoveArticleRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{27}
}

func (x *MoveArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoveArticleRequest) GetNewParentId() int64 {
	if x != nil {
		return x.NewParentId
	}
	return 0
}

func (x *MoveArticleRequest) GetKnowledgeId() int64 {
	if x != nil {
		return x.KnowledgeId
	}
	return 0
}

// 移动文章响应
type MoveArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ArticleTree   []*ArticleTreeNode     `protobuf:"bytes,3,rep,name=article_tree,json=articleTree,proto3" json:"article_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveArticleResponse) Reset() {
	*x = MoveArticleResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArticleResponse) ProtoMessage() {}

func (x *MoveArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArticleResponse.ProtoReflect.Descriptor instead.
func (*MoveArticleResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{28}
}

func (x *MoveArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveArticleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MoveArticleResponse) GetArticleTree() []*ArticleTreeNode {
	if x != nil {
		return x.ArticleTree
	}
	return nil
}

var File_knowledge_v1_knowledge_proto protoreflect.FileDescriptor

const file_knowledge_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1cknowledge/v1/knowledge.proto\x12\fknowledge.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x02\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x17\n" +
	"\aby_sort\x18\a \x01(\x03R\x06bySort\"\x14\n" +
	"\x12ListDomainsRequest\"A\n" +
	"\x13ListDomainsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.knowledge.v1.DomainR\x05items\"\xe8\x02\n" +
	"\tKnowledge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x1b\n" +
	"\tdomain_id\x18\x05 \x01(\x03R\bdomainId\x12.\n" +
	"\x13parent_knowledge_id\x18\x06 \x01(\x03R\x11parentKnowledgeId\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x17\n" +
	"\aby_sort\x18\t \x01(\x03R\x06bySort\"\xb4\x01\n" +
	"\x16CreateKnowledgeRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\x12.\n" +
	"\x13parent_knowledge_id\x18\x02 \x01(\x03R\x11parentKnowledgeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\aby_sort\x18\x05 \x01(\x03R\x06bySort\"\xc4\x01\n" +
	"\x16UpdateKnowledgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12.\n" +
	"\x13parent_knowledge_id\x18\x03 \x01(\x03R\x11parentKnowledgeId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\aby_sort\x18\x06 \x01(\x03R\x06bySort\"(\n" +
	"\x16DeleteKnowledgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\x17GetKnowledgeTreeRequest\x12\x1b\n" +
	"\tdomain_id\x18\x01 \x01(\x03R\bdomainId\"Q\n" +
	"\x18GetKnowledgeTreeResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.knowledge.v1.KnowledgeTreeNodeR\x05items\"\xfc\x01\n" +
	"\x11KnowledgeTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\x03R\bdomainId\x12.\n" +
	"\x13parent_knowledge_id\x18\x03 \x01(\x03R\x11parentKnowledgeId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\aby_sort\x18\x06 \x01(\x03R\x06bySort\x12;\n" +
	"\bchildren\x18\a \x03(\v2\x1f.knowledge.v1.KnowledgeTreeNodeR\bchildren\"\xf8\x02\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12!\n" +
	"\fknowledge_id\x18\x05 \x01(\x03R\vknowledgeId\x12*\n" +
	"\x11parent_article_id\x18\x06 \x01(\x03R\x0fparentArticleId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\t \x01(\x05R\x05level\x12\x17\n" +
	"\aby_sort\x18\n" +
	" \x01(\x03R\x06bySort\"\xc4\x01\n" +
	"\x14CreateArticleRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\x03R\vknowledgeId\x12*\n" +
	"\x11parent_article_id\x18\x02 \x01(\x03R\x0fparentArticleId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x17\n" +
	"\aby_sort\x18\x06 \x01(\x03R\x06bySort\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd4\x01\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fknowledge_id\x18\x02 \x01(\x03R\vknowledgeId\x12*\n" +
	"\x11parent_article_id\x18\x03 \x01(\x03R\x0fparentArticleId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x17\n" +
	"\aby_sort\x18\a \x01(\x03R\x06bySort\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x15GetArticleTreeRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\x03R\vknowledgeId\"M\n" +
	"\x16GetArticleTreeResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.knowledge.v1.ArticleTreeNodeR\x05items\"\x8a\x02\n" +
	"\x0fArticleTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fknowledge_id\x18\x02 \x01(\x03R\vknowledgeId\x12*\n" +
	"\x11parent_article_id\x18\x03 \x01(\x03R\x0fparentArticleId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x17\n" +
	"\aby_sort\x18\a \x01(\x03R\x06bySort\x129\n" +
	"\bchildren\x18\b \x03(\v2\x1d.knowledge.v1.ArticleTreeNodeR\bchildren\"\x80\x03\n" +
	"\x0fArticleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12!\n" +
	"\fknowledge_id\x18\x05 \x01(\x03R\vknowledgeId\x12*\n" +
	"\x11parent_article_id\x18\x06 \x01(\x03R\x0fparentArticleId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x14\n" +
	"\x05level\x18\t \x01(\x05R\x05level\x12\x17\n" +
	"\aby_sort\x18\n" +
	" \x01(\x03R\x06bySort\"M\n" +
	"\x14SortKnowledgeRequest\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.knowledge.v1.KnowledgeSortItemR\x05items\"<\n" +
	"\x11KnowledgeSortItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aby_sort\x18\x02 \x01(\x03R\x06bySort\"K\n" +
	"\x15SortKnowledgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x12SortArticleRequest\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.knowledge.v1.ArticleSortItemR\x05items\":\n" +
	"\x0fArticleSortItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aby_sort\x18\x02 \x01(\x03R\x06bySort\"\x8b\x01\n" +
	"\x13SortArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\farticle_tree\x18\x03 \x03(\v2\x1d.knowledge.v1.ArticleTreeNodeR\varticleTree\"g\n" +
	"\x14MoveKnowledgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\rnew_parent_id\x18\x02 \x01(\x03R\vnewParentId\x12\x1b\n" +
	"\tdomain_id\x18\x03 \x01(\x03R\bdomainId\"\x93\x01\n" +
	"\x15MoveKnowledgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x0eknowledge_tree\x18\x03 \x03(\v2\x1f.knowledge.v1.KnowledgeTreeNodeR\rknowledgeTree\"k\n" +
	"\x12MoveArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\"\n" +
	"\rnew_parent_id\x18\x02 \x01(\x03R\vnewParentId\x12!\n" +
	"\fknowledge_id\x18\x03 \x01(\x03R\vknowledgeId\"\x8b\x01\n" +
	"\x13MoveArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\farticle_tree\x18\x03 \x03(\v2\x1d.knowledge.v1.ArticleTreeNodeR\varticleTree2|\n" +
	"\rDomainService\x12k\n" +
	"\vListDomains\x12 .knowledge.v1.ListDomainsRequest\x1a!.knowledge.v1.ListDomainsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/domains2\xeb\x05\n" +
	"\x10KnowledgeService\x12o\n" +
	"\x0fCreateKnowledge\x12$.knowledge.v1.CreateKnowledgeRequest\x1a\x17.knowledge.v1.Knowledge\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/knowledges\x12t\n" +
	"\x0fUpdateKnowledge\x12$.knowledge.v1.UpdateKnowledgeRequest\x1a\x17.knowledge.v1.Knowledge\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/knowledges/{id}\x12p\n" +
	"\x0fDeleteKnowledge\x12$.knowledge.v1.DeleteKnowledgeRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/knowledges/{id}\x12\x81\x01\n" +
	"\x10GetKnowledgeTree\x12%.knowledge.v1.GetKnowledgeTreeRequest\x1a&.knowledge.v1.GetKnowledgeTreeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/knowledge-tree\x12|\n" +
	"\rSortKnowledge\x12\".knowledge.v1.SortKnowledgeRequest\x1a#.knowledge.v1.SortKnowledgeResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/knowledges/sort\x12|\n" +
	"\rMoveKnowledge\x12\".knowledge.v1.MoveKnowledgeRequest\x1a#.knowledge.v1.MoveKnowledgeResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/knowledges/move2\xb6\x06\n" +
	"\x0eArticleService\x12o\n" +
	"\rCreateArticle\x12\".knowledge.v1.CreateArticleRequest\x1a\x1d.knowledge.v1.ArticleResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/articles\x12c\n" +
	"\n" +
	"GetArticle\x12\x1f.knowledge.v1.GetArticleRequest\x1a\x15.knowledge.v1.Article\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/articles/{id}\x12t\n" +
	"\rUpdateArticle\x12\".knowledge.v1.UpdateArticleRequest\x1a\x1d.knowledge.v1.ArticleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/articles/{id}\x12q\n" +
	"\rDeleteArticle\x12\".knowledge.v1.DeleteArticleRequest\x1a\x1d.knowledge.v1.ArticleResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/articles/{id}\x12y\n" +
	"\x0eGetArticleTree\x12#.knowledge.v1.GetArticleTreeRequest\x1a$.knowledge.v1.GetArticleTreeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/article-tree\x12t\n" +
	"\vSortArticle\x12 .knowledge.v1.SortArticleRequest\x1a!.knowledge.v1.SortArticleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/articles/sort\x12t\n" +
	"\vMoveArticle\x12 .knowledge.v1.MoveArticleRequest\x1a!.knowledge.v1.MoveArticleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/articles/moveBT\n" +
	"\x1bdev.kratos.api.knowledge.v1B\x10KnowledgeProtoV1P\x01Z!my_knowledges/api/knowledge/v1;v1b\x06proto3"

var (
	file_knowledge_v1_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_v1_knowledge_proto_rawDescData []byte
)

func file_knowledge_v1_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)))
	})
	return file_knowledge_v1_knowledge_proto_rawDescData
}

var file_knowledge_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_knowledge_v1_knowledge_proto_goTypes = []any{
	(*Domain)(nil),                   // 0: knowledge.v1.Domain
	(*ListDomainsRequest)(nil),       // 1: knowledge.v1.ListDomainsRequest
	(*ListDomainsResponse)(nil),      // 2: knowledge.v1.ListDomainsResponse
	(*Knowledge)(nil),                // 3: knowledge.v1.Knowledge
	(*CreateKnowledgeRequest)(nil),   // 4: knowledge.v1.CreateKnowledgeRequest
	(*UpdateKnowledgeRequest)(nil),   // 5: knowledge.v1.UpdateKnowledgeRequest
	(*DeleteKnowledgeRequest)(nil),   // 6: knowledge.v1.DeleteKnowledgeRequest
	(*GetKnowledgeTreeRequest)(nil),  // 7: knowledge.v1.GetKnowledgeTreeRequest
	(*GetKnowledgeTreeResponse)(nil), // 8: knowledge.v1.GetKnowledgeTreeResponse
	(*KnowledgeTreeNode)(nil),        // 9: knowledge.v1.KnowledgeTreeNode
	(*Article)(nil),                  // 10: knowledge.v1.Article
	(*CreateArticleRequest)(nil),     // 11: knowledge.v1.CreateArticleRequest
	(*GetArticleRequest)(nil),        // 12: knowledge.v1.GetArticleRequest
	(*UpdateArticleRequest)(nil),     // 13: knowledge.v1.UpdateArticleRequest
	(*DeleteArticleRequest)(nil),     // 14: knowledge.v1.DeleteArticleRequest
	(*GetArticleTreeRequest)(nil),    // 15: knowledge.v1.GetArticleTreeRequest
	(*GetArticleTreeResponse)(nil),   // 16: knowledge.v1.GetArticleTreeResponse
	(*ArticleTreeNode)(nil),          // 17: knowledge.v1.ArticleTreeNode
	(*ArticleResponse)(nil),          // 18: knowledge.v1.ArticleResponse
	(*SortKnowledgeRequest)(nil),     // 19: knowledge.v1.SortKnowledgeRequest
	(*KnowledgeSortItem)(nil),        // 20: knowledge.v1.KnowledgeSortItem
	(*SortKnowledgeResponse)(nil),    // 21: knowledge.v1.SortKnowledgeResponse
	(*SortArticleRequest)(nil),       // 22: knowledge.v1.SortArticleRequest
	(*ArticleSortItem)(nil),          // 23: knowledge.v1.ArticleSortItem
	(*SortArticleResponse)(nil),      // 24: knowledge.v1.SortArticleResponse
	(*MoveKnowledgeRequest)(nil),     // 25: knowledge.v1.MoveKnowledgeRequest
	(*MoveKnowledgeResponse)(nil),    // 26: knowledge.v1.MoveKnowledgeResponse
	(*MoveArticleRequest)(nil),       // 27: knowledge.v1.MoveArticleRequest
	(*MoveArticleResponse)(nil),      // 28: knowledge.v1.MoveArticleResponse
	(*timestamppb.Timestamp)(nil),    // 29: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 30: google.protobuf.Empty
}
var file_knowledge_v1_knowledge_proto_depIdxs = []int32{
	29, // 0: knowledge.v1.Domain.created_at:type_name -> google.protobuf.Timestamp
	29, // 1: knowledge.v1.Domain.updated_at:type_name -> google.protobuf.Timestamp
	29, // 2: knowledge.v1.Domain.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: knowledge.v1.ListDomainsResponse.items:type_name -> knowledge.v1.Domain
	29, // 4: knowledge.v1.Knowledge.created_at:type_name -> google.protobuf.Timestamp
	29, // 5: knowledge.v1.Knowledge.updated_at:type_name -> google.protobuf.Timestamp
	29, // 6: knowledge.v1.Knowledge.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 7: knowledge.v1.GetKnowledgeTreeResponse.items:type_name -> knowledge.v1.KnowledgeTreeNode
	9,  // 8: knowledge.v1.KnowledgeTreeNode.children:type_name -> knowledge.v1.KnowledgeTreeNode
	29, // 9: knowledge.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	29, // 10: knowledge.v1.Article.updated_at:type_name -> google.protobuf.Timestamp
	29, // 11: knowledge.v1.Article.deleted_at:type_name -> google.protobuf.Timestamp
	17, // 12: knowledge.v1.GetArticleTreeResponse.items:type_name -> knowledge.v1.ArticleTreeNode
	17, // 13: knowledge.v1.ArticleTreeNode.children:type_name -> knowledge.v1.ArticleTreeNode
	29, // 14: knowledge.v1.ArticleResponse.created_at:type_name -> google.protobuf.Timestamp
	29, // 15: knowledge.v1.ArticleResponse.updated_at:type_name -> google.protobuf.Timestamp
	29, // 16: knowledge.v1.ArticleResponse.deleted_at:type_name -> google.protobuf.Timestamp
	20, // 17: knowledge.v1.SortKnowledgeRequest.items:type_name -> knowledge.v1.KnowledgeSortItem
	23, // 18: knowledge.v1.SortArticleRequest.items:type_name -> knowledge.v1.ArticleSortItem
	17, // 19: knowledge.v1.SortArticleResponse.article_tree:type_name -> knowledge.v1.ArticleTreeNode
	9,  // 20: knowledge.v1.MoveKnowledgeResponse.knowledge_tree:type_name -> knowledge.v1.KnowledgeTreeNode
	17, // 21: knowledge.v1.MoveArticleResponse.article_tree:type_name -> knowledge.v1.ArticleTreeNode
	1,  // 22: knowledge.v1.DomainService.ListDomains:input_type -> knowledge.v1.ListDomainsRequest
	4,  // 23: knowledge.v1.KnowledgeService.CreateKnowledge:input_type -> knowledge.v1.CreateKnowledgeRequest
	5,  // 24: knowledge.v1.KnowledgeService.UpdateKnowledge:input_type -> knowledge.v1.UpdateKnowledgeRequest
	6,  // 25: knowledge.v1.KnowledgeService.DeleteKnowledge:input_type -> knowledge.v1.DeleteKnowledgeRequest
	7,  // 26: knowledge.v1.KnowledgeService.GetKnowledgeTree:input_type -> knowledge.v1.GetKnowledgeTreeRequest
	19, // 27: knowledge.v1.KnowledgeService.SortKnowledge:input_type -> knowledge.v1.SortKnowledgeRequest
	25, // 28: knowledge.v1.KnowledgeService.MoveKnowledge:input_type -> knowledge.v1.MoveKnowledgeRequest
	11, // 29: knowledge.v1.ArticleService.CreateArticle:input_type -> knowledge.v1.CreateArticleRequest
	12, // 30: knowledge.v1.ArticleService.GetArticle:input_type -> knowledge.v1.GetArticleRequest
	13, // 31: knowledge.v1.ArticleService.UpdateArticle:input_type -> knowledge.v1.UpdateArticleRequest
	14, // 32: knowledge.v1.ArticleService.DeleteArticle:input_type -> knowledge.v1.DeleteArticleRequest
	15, // 33: knowledge.v1.ArticleService.GetArticleTree:input_type -> knowledge.v1.GetArticleTreeRequest
	22, // 34: knowledge.v1.ArticleService.SortArticle:input_type -> knowledge.v1.SortArticleRequest
	27, // 35: knowledge.v1.ArticleService.MoveArticle:input_type -> knowledge.v1.MoveArticleRequest
	2,  // 36: knowledge.v1.DomainService.ListDomains:output_type -> knowledge.v1.ListDomainsResponse
	3,  // 37: knowledge.v1.KnowledgeService.CreateKnowledge:output_type -> knowledge.v1.Knowledge
	3,  // 38: knowledge.v1.KnowledgeService.UpdateKnowledge:output_type -> knowledge.v1.Knowledge
	30, // 39: knowledge.v1.KnowledgeService.DeleteKnowledge:output_type -> google.protobuf.Empty
	8,  // 40: knowledge.v1.KnowledgeService.GetKnowledgeTree:output_type -> knowledge.v1.GetKnowledgeTreeResponse
	21, // 41: knowledge.v1.KnowledgeService.SortKnowledge:output_type -> knowledge.v1.SortKnowledgeResponse
	26, // 42: knowledge.v1.KnowledgeService.MoveKnowledge:output_type -> knowledge.v1.MoveKnowledgeResponse
	18, // 43: knowledge.v1.ArticleService.CreateArticle:output_type -> knowledge.v1.ArticleResponse
	10, // 44: knowledge.v1.ArticleService.GetArticle:output_type -> knowledge.v1.Article
	18, // 45: knowledge.v1.ArticleService.UpdateArticle:output_type -> knowledge.v1.ArticleResponse
	18, // 46: knowledge.v1.ArticleService.DeleteArticle:output_type -> knowledge.v1.ArticleResponse
	16, // 47: knowledge.v1.ArticleService.GetArticleTree:output_type -> knowledge.v1.GetArticleTreeResponse
	24, // 48: knowledge.v1.ArticleService.SortArticle:output_type -> knowledge.v1.SortArticleResponse
	28, // 49: knowledge.v1.ArticleService.MoveArticle:output_type -> knowledge.v1.MoveArticleResponse
	36, // [36:50] is the sub-list for method output_type
	22, // [22:36] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_knowledge_v1_knowledge_proto_init() }
func file_knowledge_v1_knowledge_proto_init() {
	if File_knowledge_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_knowledge_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_knowledge_v1_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_v1_knowledge_proto = out.File
	file_knowledge_v1_knowledge_proto_goTypes = nil
	file_knowledge_v1_knowledge_proto_depIdxs = nil
}
