// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.35.0
// source: knowledge/v1/knowledge.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDomainServiceListDomains = "/knowledge.v1.DomainService/ListDomains"

type DomainServiceHTTPServer interface {
	// ListDomains 获取领域列表
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
}

func RegisterDomainServiceHTTPServer(s *http.Server, srv DomainServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/domains", _DomainService_ListDomains0_HTTP_Handler(srv))
}

func _DomainService_ListDomains0_HTTP_Handler(srv DomainServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDomainsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDomainServiceListDomains)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDomains(ctx, req.(*ListDomainsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDomainsResponse)
		return ctx.Result(200, reply)
	}
}

type DomainServiceHTTPClient interface {
	// ListDomains 获取领域列表
	ListDomains(ctx context.Context, req *ListDomainsRequest, opts ...http.CallOption) (rsp *ListDomainsResponse, err error)
}

type DomainServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDomainServiceHTTPClient(client *http.Client) DomainServiceHTTPClient {
	return &DomainServiceHTTPClientImpl{client}
}

// ListDomains 获取领域列表
func (c *DomainServiceHTTPClientImpl) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...http.CallOption) (*ListDomainsResponse, error) {
	var out ListDomainsResponse
	pattern := "/api/v1/domains"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDomainServiceListDomains))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationKnowledgeServiceCreateKnowledge = "/knowledge.v1.KnowledgeService/CreateKnowledge"
const OperationKnowledgeServiceDeleteKnowledge = "/knowledge.v1.KnowledgeService/DeleteKnowledge"
const OperationKnowledgeServiceGetKnowledgeTree = "/knowledge.v1.KnowledgeService/GetKnowledgeTree"
const OperationKnowledgeServiceMoveKnowledge = "/knowledge.v1.KnowledgeService/MoveKnowledge"
const OperationKnowledgeServiceSortKnowledge = "/knowledge.v1.KnowledgeService/SortKnowledge"
const OperationKnowledgeServiceUpdateKnowledge = "/knowledge.v1.KnowledgeService/UpdateKnowledge"

type KnowledgeServiceHTTPServer interface {
	// CreateKnowledge 创建知识库
	CreateKnowledge(context.Context, *CreateKnowledgeRequest) (*Knowledge, error)
	// DeleteKnowledge 删除知识库
	DeleteKnowledge(context.Context, *DeleteKnowledgeRequest) (*emptypb.Empty, error)
	// GetKnowledgeTree 获取知识库树
	GetKnowledgeTree(context.Context, *GetKnowledgeTreeRequest) (*GetKnowledgeTreeResponse, error)
	// MoveKnowledge 移动知识库
	MoveKnowledge(context.Context, *MoveKnowledgeRequest) (*MoveKnowledgeResponse, error)
	// SortKnowledge 排序知识库
	SortKnowledge(context.Context, *SortKnowledgeRequest) (*SortKnowledgeResponse, error)
	// UpdateKnowledge 更新知识库
	UpdateKnowledge(context.Context, *UpdateKnowledgeRequest) (*Knowledge, error)
}

func RegisterKnowledgeServiceHTTPServer(s *http.Server, srv KnowledgeServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/knowledges", _KnowledgeService_CreateKnowledge0_HTTP_Handler(srv))
	r.PUT("/api/v1/knowledges/{id}", _KnowledgeService_UpdateKnowledge0_HTTP_Handler(srv))
	r.DELETE("/api/v1/knowledges/{id}", _KnowledgeService_DeleteKnowledge0_HTTP_Handler(srv))
	r.GET("/api/v1/knowledge-tree", _KnowledgeService_GetKnowledgeTree0_HTTP_Handler(srv))
	r.POST("/api/v1/knowledges/sort", _KnowledgeService_SortKnowledge0_HTTP_Handler(srv))
	r.POST("/api/v1/knowledges/move", _KnowledgeService_MoveKnowledge0_HTTP_Handler(srv))
}

func _KnowledgeService_CreateKnowledge0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceCreateKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKnowledge(ctx, req.(*CreateKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Knowledge)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_UpdateKnowledge0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceUpdateKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKnowledge(ctx, req.(*UpdateKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Knowledge)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_DeleteKnowledge0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteKnowledgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceDeleteKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKnowledge(ctx, req.(*DeleteKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_GetKnowledgeTree0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKnowledgeTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceGetKnowledgeTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKnowledgeTree(ctx, req.(*GetKnowledgeTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetKnowledgeTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_SortKnowledge0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SortKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceSortKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SortKnowledge(ctx, req.(*SortKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SortKnowledgeResponse)
		return ctx.Result(200, reply)
	}
}

func _KnowledgeService_MoveKnowledge0_HTTP_Handler(srv KnowledgeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MoveKnowledgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKnowledgeServiceMoveKnowledge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MoveKnowledge(ctx, req.(*MoveKnowledgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoveKnowledgeResponse)
		return ctx.Result(200, reply)
	}
}

type KnowledgeServiceHTTPClient interface {
	// CreateKnowledge 创建知识库
	CreateKnowledge(ctx context.Context, req *CreateKnowledgeRequest, opts ...http.CallOption) (rsp *Knowledge, err error)
	// DeleteKnowledge 删除知识库
	DeleteKnowledge(ctx context.Context, req *DeleteKnowledgeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetKnowledgeTree 获取知识库树
	GetKnowledgeTree(ctx context.Context, req *GetKnowledgeTreeRequest, opts ...http.CallOption) (rsp *GetKnowledgeTreeResponse, err error)
	// MoveKnowledge 移动知识库
	MoveKnowledge(ctx context.Context, req *MoveKnowledgeRequest, opts ...http.CallOption) (rsp *MoveKnowledgeResponse, err error)
	// SortKnowledge 排序知识库
	SortKnowledge(ctx context.Context, req *SortKnowledgeRequest, opts ...http.CallOption) (rsp *SortKnowledgeResponse, err error)
	// UpdateKnowledge 更新知识库
	UpdateKnowledge(ctx context.Context, req *UpdateKnowledgeRequest, opts ...http.CallOption) (rsp *Knowledge, err error)
}

type KnowledgeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewKnowledgeServiceHTTPClient(client *http.Client) KnowledgeServiceHTTPClient {
	return &KnowledgeServiceHTTPClientImpl{client}
}

// CreateKnowledge 创建知识库
func (c *KnowledgeServiceHTTPClientImpl) CreateKnowledge(ctx context.Context, in *CreateKnowledgeRequest, opts ...http.CallOption) (*Knowledge, error) {
	var out Knowledge
	pattern := "/api/v1/knowledges"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceCreateKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteKnowledge 删除知识库
func (c *KnowledgeServiceHTTPClientImpl) DeleteKnowledge(ctx context.Context, in *DeleteKnowledgeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/knowledges/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceDeleteKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetKnowledgeTree 获取知识库树
func (c *KnowledgeServiceHTTPClientImpl) GetKnowledgeTree(ctx context.Context, in *GetKnowledgeTreeRequest, opts ...http.CallOption) (*GetKnowledgeTreeResponse, error) {
	var out GetKnowledgeTreeResponse
	pattern := "/api/v1/knowledge-tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKnowledgeServiceGetKnowledgeTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MoveKnowledge 移动知识库
func (c *KnowledgeServiceHTTPClientImpl) MoveKnowledge(ctx context.Context, in *MoveKnowledgeRequest, opts ...http.CallOption) (*MoveKnowledgeResponse, error) {
	var out MoveKnowledgeResponse
	pattern := "/api/v1/knowledges/move"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceMoveKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SortKnowledge 排序知识库
func (c *KnowledgeServiceHTTPClientImpl) SortKnowledge(ctx context.Context, in *SortKnowledgeRequest, opts ...http.CallOption) (*SortKnowledgeResponse, error) {
	var out SortKnowledgeResponse
	pattern := "/api/v1/knowledges/sort"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceSortKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateKnowledge 更新知识库
func (c *KnowledgeServiceHTTPClientImpl) UpdateKnowledge(ctx context.Context, in *UpdateKnowledgeRequest, opts ...http.CallOption) (*Knowledge, error) {
	var out Knowledge
	pattern := "/api/v1/knowledges/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKnowledgeServiceUpdateKnowledge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationArticleServiceCreateArticle = "/knowledge.v1.ArticleService/CreateArticle"
const OperationArticleServiceDeleteArticle = "/knowledge.v1.ArticleService/DeleteArticle"
const OperationArticleServiceGetArticle = "/knowledge.v1.ArticleService/GetArticle"
const OperationArticleServiceGetArticleTree = "/knowledge.v1.ArticleService/GetArticleTree"
const OperationArticleServiceMoveArticle = "/knowledge.v1.ArticleService/MoveArticle"
const OperationArticleServiceSortArticle = "/knowledge.v1.ArticleService/SortArticle"
const OperationArticleServiceUpdateArticle = "/knowledge.v1.ArticleService/UpdateArticle"

type ArticleServiceHTTPServer interface {
	// CreateArticle 创建文章
	CreateArticle(context.Context, *CreateArticleRequest) (*ArticleResponse, error)
	// DeleteArticle 删除文章
	DeleteArticle(context.Context, *DeleteArticleRequest) (*ArticleResponse, error)
	// GetArticle 获取单个文章
	GetArticle(context.Context, *GetArticleRequest) (*Article, error)
	// GetArticleTree 获取文章树
	GetArticleTree(context.Context, *GetArticleTreeRequest) (*GetArticleTreeResponse, error)
	// MoveArticle 移动文章
	MoveArticle(context.Context, *MoveArticleRequest) (*MoveArticleResponse, error)
	// SortArticle 排序文章
	SortArticle(context.Context, *SortArticleRequest) (*SortArticleResponse, error)
	// UpdateArticle 更新文章
	UpdateArticle(context.Context, *UpdateArticleRequest) (*ArticleResponse, error)
}

func RegisterArticleServiceHTTPServer(s *http.Server, srv ArticleServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/articles", _ArticleService_CreateArticle0_HTTP_Handler(srv))
	r.GET("/api/v1/articles/{id}", _ArticleService_GetArticle0_HTTP_Handler(srv))
	r.PUT("/api/v1/articles/{id}", _ArticleService_UpdateArticle0_HTTP_Handler(srv))
	r.DELETE("/api/v1/articles/{id}", _ArticleService_DeleteArticle0_HTTP_Handler(srv))
	r.GET("/api/v1/article-tree", _ArticleService_GetArticleTree0_HTTP_Handler(srv))
	r.POST("/api/v1/articles/sort", _ArticleService_SortArticle0_HTTP_Handler(srv))
	r.POST("/api/v1/articles/move", _ArticleService_MoveArticle0_HTTP_Handler(srv))
}

func _ArticleService_CreateArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceCreateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateArticle(ctx, req.(*CreateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_GetArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceGetArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticle(ctx, req.(*GetArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Article)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_UpdateArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceUpdateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateArticle(ctx, req.(*UpdateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_DeleteArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceDeleteArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteArticle(ctx, req.(*DeleteArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_GetArticleTree0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArticleTreeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceGetArticleTree)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticleTree(ctx, req.(*GetArticleTreeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArticleTreeResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_SortArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SortArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceSortArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SortArticle(ctx, req.(*SortArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SortArticleResponse)
		return ctx.Result(200, reply)
	}
}

func _ArticleService_MoveArticle0_HTTP_Handler(srv ArticleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MoveArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationArticleServiceMoveArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MoveArticle(ctx, req.(*MoveArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MoveArticleResponse)
		return ctx.Result(200, reply)
	}
}

type ArticleServiceHTTPClient interface {
	// CreateArticle 创建文章
	CreateArticle(ctx context.Context, req *CreateArticleRequest, opts ...http.CallOption) (rsp *ArticleResponse, err error)
	// DeleteArticle 删除文章
	DeleteArticle(ctx context.Context, req *DeleteArticleRequest, opts ...http.CallOption) (rsp *ArticleResponse, err error)
	// GetArticle 获取单个文章
	GetArticle(ctx context.Context, req *GetArticleRequest, opts ...http.CallOption) (rsp *Article, err error)
	// GetArticleTree 获取文章树
	GetArticleTree(ctx context.Context, req *GetArticleTreeRequest, opts ...http.CallOption) (rsp *GetArticleTreeResponse, err error)
	// MoveArticle 移动文章
	MoveArticle(ctx context.Context, req *MoveArticleRequest, opts ...http.CallOption) (rsp *MoveArticleResponse, err error)
	// SortArticle 排序文章
	SortArticle(ctx context.Context, req *SortArticleRequest, opts ...http.CallOption) (rsp *SortArticleResponse, err error)
	// UpdateArticle 更新文章
	UpdateArticle(ctx context.Context, req *UpdateArticleRequest, opts ...http.CallOption) (rsp *ArticleResponse, err error)
}

type ArticleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewArticleServiceHTTPClient(client *http.Client) ArticleServiceHTTPClient {
	return &ArticleServiceHTTPClientImpl{client}
}

// CreateArticle 创建文章
func (c *ArticleServiceHTTPClientImpl) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...http.CallOption) (*ArticleResponse, error) {
	var out ArticleResponse
	pattern := "/api/v1/articles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceCreateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteArticle 删除文章
func (c *ArticleServiceHTTPClientImpl) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...http.CallOption) (*ArticleResponse, error) {
	var out ArticleResponse
	pattern := "/api/v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceDeleteArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetArticle 获取单个文章
func (c *ArticleServiceHTTPClientImpl) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...http.CallOption) (*Article, error) {
	var out Article
	pattern := "/api/v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceGetArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetArticleTree 获取文章树
func (c *ArticleServiceHTTPClientImpl) GetArticleTree(ctx context.Context, in *GetArticleTreeRequest, opts ...http.CallOption) (*GetArticleTreeResponse, error) {
	var out GetArticleTreeResponse
	pattern := "/api/v1/article-tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationArticleServiceGetArticleTree))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MoveArticle 移动文章
func (c *ArticleServiceHTTPClientImpl) MoveArticle(ctx context.Context, in *MoveArticleRequest, opts ...http.CallOption) (*MoveArticleResponse, error) {
	var out MoveArticleResponse
	pattern := "/api/v1/articles/move"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceMoveArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SortArticle 排序文章
func (c *ArticleServiceHTTPClientImpl) SortArticle(ctx context.Context, in *SortArticleRequest, opts ...http.CallOption) (*SortArticleResponse, error) {
	var out SortArticleResponse
	pattern := "/api/v1/articles/sort"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceSortArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateArticle 更新文章
func (c *ArticleServiceHTTPClientImpl) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...http.CallOption) (*ArticleResponse, error) {
	var out ArticleResponse
	pattern := "/api/v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationArticleServiceUpdateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
