// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: knowledge/v1/knowledge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DomainService_ListDomains_FullMethodName = "/knowledge.v1.DomainService/ListDomains"
)

// DomainServiceClient is the client API for DomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 领域服务
type DomainServiceClient interface {
	// 获取领域列表
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
}

type domainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainServiceClient(cc grpc.ClientConnInterface) DomainServiceClient {
	return &domainServiceClient{cc}
}

func (c *domainServiceClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, DomainService_ListDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainServiceServer is the server API for DomainService service.
// All implementations must embed UnimplementedDomainServiceServer
// for forward compatibility.
//
// 领域服务
type DomainServiceServer interface {
	// 获取领域列表
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
	mustEmbedUnimplementedDomainServiceServer()
}

// UnimplementedDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDomainServiceServer struct{}

func (UnimplementedDomainServiceServer) ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomains not implemented")
}
func (UnimplementedDomainServiceServer) mustEmbedUnimplementedDomainServiceServer() {}
func (UnimplementedDomainServiceServer) testEmbeddedByValue()                       {}

// UnsafeDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainServiceServer will
// result in compilation errors.
type UnsafeDomainServiceServer interface {
	mustEmbedUnimplementedDomainServiceServer()
}

func RegisterDomainServiceServer(s grpc.ServiceRegistrar, srv DomainServiceServer) {
	// If the following call pancis, it indicates UnimplementedDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DomainService_ServiceDesc, srv)
}

func _DomainService_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainServiceServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainService_ListDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainServiceServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainService_ServiceDesc is the grpc.ServiceDesc for DomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.v1.DomainService",
	HandlerType: (*DomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDomains",
			Handler:    _DomainService_ListDomains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/v1/knowledge.proto",
}

const (
	KnowledgeService_CreateKnowledge_FullMethodName  = "/knowledge.v1.KnowledgeService/CreateKnowledge"
	KnowledgeService_UpdateKnowledge_FullMethodName  = "/knowledge.v1.KnowledgeService/UpdateKnowledge"
	KnowledgeService_DeleteKnowledge_FullMethodName  = "/knowledge.v1.KnowledgeService/DeleteKnowledge"
	KnowledgeService_GetKnowledgeTree_FullMethodName = "/knowledge.v1.KnowledgeService/GetKnowledgeTree"
	KnowledgeService_SortKnowledge_FullMethodName    = "/knowledge.v1.KnowledgeService/SortKnowledge"
	KnowledgeService_MoveKnowledge_FullMethodName    = "/knowledge.v1.KnowledgeService/MoveKnowledge"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 知识库服务
type KnowledgeServiceClient interface {
	// 创建知识库
	CreateKnowledge(ctx context.Context, in *CreateKnowledgeRequest, opts ...grpc.CallOption) (*Knowledge, error)
	// 更新知识库
	UpdateKnowledge(ctx context.Context, in *UpdateKnowledgeRequest, opts ...grpc.CallOption) (*Knowledge, error)
	// 删除知识库
	DeleteKnowledge(ctx context.Context, in *DeleteKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取知识库树
	GetKnowledgeTree(ctx context.Context, in *GetKnowledgeTreeRequest, opts ...grpc.CallOption) (*GetKnowledgeTreeResponse, error)
	// 排序知识库
	SortKnowledge(ctx context.Context, in *SortKnowledgeRequest, opts ...grpc.CallOption) (*SortKnowledgeResponse, error)
	// 移动知识库
	MoveKnowledge(ctx context.Context, in *MoveKnowledgeRequest, opts ...grpc.CallOption) (*MoveKnowledgeResponse, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreateKnowledge(ctx context.Context, in *CreateKnowledgeRequest, opts ...grpc.CallOption) (*Knowledge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Knowledge)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) UpdateKnowledge(ctx context.Context, in *UpdateKnowledgeRequest, opts ...grpc.CallOption) (*Knowledge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Knowledge)
	err := c.cc.Invoke(ctx, KnowledgeService_UpdateKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) DeleteKnowledge(ctx context.Context, in *DeleteKnowledgeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeService_DeleteKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetKnowledgeTree(ctx context.Context, in *GetKnowledgeTreeRequest, opts ...grpc.CallOption) (*GetKnowledgeTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgeTreeResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GetKnowledgeTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) SortKnowledge(ctx context.Context, in *SortKnowledgeRequest, opts ...grpc.CallOption) (*SortKnowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortKnowledgeResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_SortKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) MoveKnowledge(ctx context.Context, in *MoveKnowledgeRequest, opts ...grpc.CallOption) (*MoveKnowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveKnowledgeResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_MoveKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
//
// 知识库服务
type KnowledgeServiceServer interface {
	// 创建知识库
	CreateKnowledge(context.Context, *CreateKnowledgeRequest) (*Knowledge, error)
	// 更新知识库
	UpdateKnowledge(context.Context, *UpdateKnowledgeRequest) (*Knowledge, error)
	// 删除知识库
	DeleteKnowledge(context.Context, *DeleteKnowledgeRequest) (*emptypb.Empty, error)
	// 获取知识库树
	GetKnowledgeTree(context.Context, *GetKnowledgeTreeRequest) (*GetKnowledgeTreeResponse, error)
	// 排序知识库
	SortKnowledge(context.Context, *SortKnowledgeRequest) (*SortKnowledgeResponse, error)
	// 移动知识库
	MoveKnowledge(context.Context, *MoveKnowledgeRequest) (*MoveKnowledgeResponse, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) CreateKnowledge(context.Context, *CreateKnowledgeRequest) (*Knowledge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledge not implemented")
}
func (UnimplementedKnowledgeServiceServer) UpdateKnowledge(context.Context, *UpdateKnowledgeRequest) (*Knowledge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledge not implemented")
}
func (UnimplementedKnowledgeServiceServer) DeleteKnowledge(context.Context, *DeleteKnowledgeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledge not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetKnowledgeTree(context.Context, *GetKnowledgeTreeRequest) (*GetKnowledgeTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeTree not implemented")
}
func (UnimplementedKnowledgeServiceServer) SortKnowledge(context.Context, *SortKnowledgeRequest) (*SortKnowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortKnowledge not implemented")
}
func (UnimplementedKnowledgeServiceServer) MoveKnowledge(context.Context, *MoveKnowledgeRequest) (*MoveKnowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveKnowledge not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue()                          {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreateKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateKnowledge(ctx, req.(*CreateKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_UpdateKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).UpdateKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_UpdateKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).UpdateKnowledge(ctx, req.(*UpdateKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_DeleteKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).DeleteKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_DeleteKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).DeleteKnowledge(ctx, req.(*DeleteKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetKnowledgeTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetKnowledgeTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetKnowledgeTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetKnowledgeTree(ctx, req.(*GetKnowledgeTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_SortKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).SortKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_SortKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).SortKnowledge(ctx, req.(*SortKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_MoveKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).MoveKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_MoveKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).MoveKnowledge(ctx, req.(*MoveKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.v1.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledge",
			Handler:    _KnowledgeService_CreateKnowledge_Handler,
		},
		{
			MethodName: "UpdateKnowledge",
			Handler:    _KnowledgeService_UpdateKnowledge_Handler,
		},
		{
			MethodName: "DeleteKnowledge",
			Handler:    _KnowledgeService_DeleteKnowledge_Handler,
		},
		{
			MethodName: "GetKnowledgeTree",
			Handler:    _KnowledgeService_GetKnowledgeTree_Handler,
		},
		{
			MethodName: "SortKnowledge",
			Handler:    _KnowledgeService_SortKnowledge_Handler,
		},
		{
			MethodName: "MoveKnowledge",
			Handler:    _KnowledgeService_MoveKnowledge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/v1/knowledge.proto",
}

const (
	ArticleService_CreateArticle_FullMethodName  = "/knowledge.v1.ArticleService/CreateArticle"
	ArticleService_GetArticle_FullMethodName     = "/knowledge.v1.ArticleService/GetArticle"
	ArticleService_UpdateArticle_FullMethodName  = "/knowledge.v1.ArticleService/UpdateArticle"
	ArticleService_DeleteArticle_FullMethodName  = "/knowledge.v1.ArticleService/DeleteArticle"
	ArticleService_GetArticleTree_FullMethodName = "/knowledge.v1.ArticleService/GetArticleTree"
	ArticleService_SortArticle_FullMethodName    = "/knowledge.v1.ArticleService/SortArticle"
	ArticleService_MoveArticle_FullMethodName    = "/knowledge.v1.ArticleService/MoveArticle"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 文章服务
type ArticleServiceClient interface {
	// 创建文章
	CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	// 获取单个文章
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error)
	// 更新文章
	UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	// 删除文章
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	// 获取文章树
	GetArticleTree(ctx context.Context, in *GetArticleTreeRequest, opts ...grpc.CallOption) (*GetArticleTreeResponse, error)
	// 排序文章
	SortArticle(ctx context.Context, in *SortArticleRequest, opts ...grpc.CallOption) (*SortArticleResponse, error)
	// 移动文章
	MoveArticle(ctx context.Context, in *MoveArticleRequest, opts ...grpc.CallOption) (*MoveArticleResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) CreateArticle(ctx context.Context, in *CreateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_CreateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*Article, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Article)
	err := c.cc.Invoke(ctx, ArticleService_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleTree(ctx context.Context, in *GetArticleTreeRequest, opts ...grpc.CallOption) (*GetArticleTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleTreeResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) SortArticle(ctx context.Context, in *SortArticleRequest, opts ...grpc.CallOption) (*SortArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SortArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_SortArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) MoveArticle(ctx context.Context, in *MoveArticleRequest, opts ...grpc.CallOption) (*MoveArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_MoveArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
//
// 文章服务
type ArticleServiceServer interface {
	// 创建文章
	CreateArticle(context.Context, *CreateArticleRequest) (*ArticleResponse, error)
	// 获取单个文章
	GetArticle(context.Context, *GetArticleRequest) (*Article, error)
	// 更新文章
	UpdateArticle(context.Context, *UpdateArticleRequest) (*ArticleResponse, error)
	// 删除文章
	DeleteArticle(context.Context, *DeleteArticleRequest) (*ArticleResponse, error)
	// 获取文章树
	GetArticleTree(context.Context, *GetArticleTreeRequest) (*GetArticleTreeResponse, error)
	// 排序文章
	SortArticle(context.Context, *SortArticleRequest) (*SortArticleResponse, error)
	// 移动文章
	MoveArticle(context.Context, *MoveArticleRequest) (*MoveArticleResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) CreateArticle(context.Context, *CreateArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedArticleServiceServer) GetArticle(context.Context, *GetArticleRequest) (*Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedArticleServiceServer) UpdateArticle(context.Context, *UpdateArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedArticleServiceServer) DeleteArticle(context.Context, *DeleteArticleRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleTree(context.Context, *GetArticleTreeRequest) (*GetArticleTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleTree not implemented")
}
func (UnimplementedArticleServiceServer) SortArticle(context.Context, *SortArticleRequest) (*SortArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortArticle not implemented")
}
func (UnimplementedArticleServiceServer) MoveArticle(context.Context, *MoveArticleRequest) (*MoveArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveArticle not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_CreateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).CreateArticle(ctx, req.(*CreateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).UpdateArticle(ctx, req.(*UpdateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleTree(ctx, req.(*GetArticleTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_SortArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).SortArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_SortArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).SortArticle(ctx, req.(*SortArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_MoveArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).MoveArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_MoveArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).MoveArticle(ctx, req.(*MoveArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.v1.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArticle",
			Handler:    _ArticleService_CreateArticle_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _ArticleService_GetArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _ArticleService_UpdateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _ArticleService_DeleteArticle_Handler,
		},
		{
			MethodName: "GetArticleTree",
			Handler:    _ArticleService_GetArticleTree_Handler,
		},
		{
			MethodName: "SortArticle",
			Handler:    _ArticleService_SortArticle_Handler,
		},
		{
			MethodName: "MoveArticle",
			Handler:    _ArticleService_MoveArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/v1/knowledge.proto",
}
